FROM php:7.1-fpm
RUN apt-get update && \
    apt-get install libldap2-dev -y && \
    docker-php-ext-configure ldap  --with-libdir=lib/x86_64-linux-gnu && \
    docker-php-ext-install ldap && \
    docker-php-ext-install pdo_mysql